In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("./googleplaystore_user_reviews.csv")

In [3]:
data.head()

App                                  Translated_Review  \
0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...   
1  10 Best Foods for You    This help eating healthy exercise regular basis   
2  10 Best Foods for You                                                NaN   
3  10 Best Foods for You         Works great especially going grocery store   
4  10 Best Foods for You                                       Best idea us   

  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  
0  Positive                1.00                0.533333  
1  Positive                0.25                0.288462  
2       NaN                 NaN                     NaN  
3  Positive                0.40                0.875000  
4  Positive                1.00                0.300000

In [4]:
df = pd.concat([data['Translated_Review'],data['Sentiment']],axis=1)
df.shape

(64295, 2)

In [5]:
df.isna().sum()

Translated_Review    26868
Sentiment            26863
dtype: int64

In [6]:
df.dropna(axis=0,inplace=True)

In [7]:
df.shape

(37427, 2)

In [8]:
df['Sentiment'].value_counts()

Positive    23998
Negative     8271
Neutral      5158
Name: Sentiment, dtype: int64

In [9]:
df.Sentiment=[0 if i=="Positive" else 1 if i== "Negative" else 2 for i in df.Sentiment]

In [10]:
import re
first_text=df.Translated_Review[0]
text=re.sub("[^a-zA-Z]"," ",first_text) #replacing every character other than alphabets, with space
text=text.lower()

In [11]:
df.Translated_Review[0]

'I like eat delicious food. That\'s I\'m cooking food myself, case "10 Best Foods" helps lot, also "Best Before (Shelf Life)"'

In [12]:
text

'i like eat delicious food  that s i m cooking food myself  case     best foods  helps lot  also  best before  shelf life  '

In [13]:
# in anaconda prompt: python -m nltk.downloader all

import nltk
# nltk.download('punkt')
from nltk.corpus import stopwords  # stopwords are not needed words like "the"
text=nltk.word_tokenize(text) # word_tokenize-separate all words

In [14]:
text

['i',
 'like',
 'eat',
 'delicious',
 'food',
 'that',
 's',
 'i',
 'm',
 'cooking',
 'food',
 'myself',
 'case',
 'best',
 'foods',
 'helps',
 'lot',
 'also',
 'best',
 'before',
 'shelf',
 'life']

In [15]:
len(text)

22

In [16]:
#  lemmatizer- considers raining as rain

In [17]:
import nltk as nlp
# nltk.download('wordnet')
lemma=nlp.WordNetLemmatizer()
text=[lemma.lemmatize(i) for i in text]
text=" ".join(text)
text

'i like eat delicious food that s i m cooking food myself case best food help lot also best before shelf life'

In [18]:
text_list=[]
for i in df.Translated_Review:
    text=re.sub("[^a-zA-Z]"," ",i)
    text=text.lower()
    text=nltk.word_tokenize(text)
    lemma=nlp.WordNetLemmatizer()
    text=[lemma.lemmatize(word) for word in text]
    text=" ".join(text)
    text_list.append(text)

In [19]:
text_list

['i like eat delicious food that s i m cooking food myself case best food help lot also best before shelf life',
 'this help eating healthy exercise regular basis',
 'work great especially going grocery store',
 'best idea u',
 'best way',
 'amazing',
 'looking forward app',
 'it helpful site it help food get',
 'good you',
 'useful information the amount spelling error question validity information shared once fixed star given',
 'thank you great app add arthritis eye immunity kidney liver detox food please',
 'greatest ever completely awesome maintain health this must ppl there love it',
 'good health good health first priority',
 'health it s important world either life think',
 'mr sunita bhati i thankful developer to make kind app really good healthy food body',
 'very useful in diabetes age i need control sugar thanks',
 'one greatest apps',
 'good nice',
 'healthy really helped',
 'god health',
 'health should always be top priority on mysg',
 'an excellent a useful',
 'i found 

In [20]:
#bag of words
from sklearn.feature_extraction.text import CountVectorizer
max_features=200000
cou_vec=CountVectorizer(max_features=max_features,stop_words="english")
sparce_matrix=cou_vec.fit_transform(text_list).toarray()
all_words=cou_vec.get_feature_names()
print("Most used words: ",all_words[50:100])

Most used words:  ['aborted', 'aborting', 'abortion', 'abou', 'abousolutely', 'abracadabra', 'abroad', 'abrupt', 'abruptly', 'absence', 'absent', 'absolute', 'absolutely', 'absolutly', 'absorbing', 'abstract', 'abstraction', 'absurd', 'abt', 'abu', 'abundance', 'abundant', 'abundantly', 'abuse', 'abused', 'abuser', 'abusing', 'abusive', 'abysmal', 'abyss', 'ac', 'aca', 'academia', 'acc', 'accasionly', 'accelent', 'accelerate', 'acceleration', 'accent', 'accentuates', 'accept', 'acceptable', 'acceptance', 'accepted', 'accepting', 'accepts', 'acces', 'accesable', 'access', 'accessabilty']


In [21]:
all_words

['aa',
 'aaa',
 'aaaaaaa',
 'aaaaaaaaaa',
 'aaadddsss',
 'aaand',
 'aah',
 'aahhh',
 'aaid',
 'aamiin',
 'aana',
 'aap',
 'aaps',
 'aarav',
 'aargh',
 'aavantage',
 'ab',
 'aback',
 'abad',
 'abandon',
 'abandoned',
 'abandonware',
 'abb',
 'abbi',
 'abbreviate',
 'abbreviated',
 'abc',
 'abcd',
 'abcmouse',
 'abd',
 'abdominal',
 'abducted',
 'abdullah',
 'abdulsallaam',
 'abegail',
 'abet',
 'abhay',
 'abhorrent',
 'abiblity',
 'ability',
 'abit',
 'abke',
 'abl',
 'able',
 'abnb',
 'abnormal',
 'abnormally',
 'abode',
 'abolish',
 'abomination',
 'aborted',
 'aborting',
 'abortion',
 'abou',
 'abousolutely',
 'abracadabra',
 'abroad',
 'abrupt',
 'abruptly',
 'absence',
 'absent',
 'absolute',
 'absolutely',
 'absolutly',
 'absorbing',
 'abstract',
 'abstraction',
 'absurd',
 'abt',
 'abu',
 'abundance',
 'abundant',
 'abundantly',
 'abuse',
 'abused',
 'abuser',
 'abusing',
 'abusive',
 'abysmal',
 'abyss',
 'ac',
 'aca',
 'academia',
 'acc',
 'accasionly',
 'accelent',
 'accelerat

In [22]:
cou_vec

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=200000, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [23]:
y=df.iloc[:,1].values
x=sparce_matrix
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [24]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
y

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [26]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
print("lr accuracy: ",lr.score(x_test,y_test))

lr accuracy:  0.9084958589366818


In [27]:
np.unique(y)

array([0, 1, 2], dtype=int64)

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
np.sqrt(37427)

193.4605903020044

In [30]:
classifier = KNeighborsClassifier(n_neighbors=193,metric='minkowski',p=2) 

In [ ]:
classifier.fit(x_train,y_train)